version: '2'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server

  frontend:
    build: ./frontend
    restart: always
    environment:
      - API_FETCH=/api/list
    depends_on:
      - nginx
      - server

  server:
    build: ./server
    restart: always
    environment:
      - API_URL=https://fe.gy/copyright-free-content/
      - SECRET=2614cff67e2b4990700438e8241b66e7
      - FLAG=codegate2023{can_we_caLL_this_a_0day?vend0r_says_it_is_the_developers_mistake_to_code_like_this}
      - REDIS_URL_CACHE=redis://redis:6379/0
      - REDIS_URL_QUERY=redis://redis:6379/1
      - STATIC_HOST=/api/
      - DIFFICULTY=6
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
    links:
      - redis

  redis:
    image: redis:5
    command: "redis-server /redis.conf"
    volumes:
      - ./redis/redis.conf:/redis.conf
    restart: always
    mem_limit: 512M

  worker:
    build: ./worker
    environment:
      - SECRET=2614cff67e2b4990700438e8241b66e7
    links:
      - nginx
      - redis
    restart: always
